# Generated by Django 5.0.7 on 2024-07-17 10:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rick_and_morty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='choice_text',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='votes',
        ),
        migrations.AddField(
            model_name='character',
            name='character_created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date field'),
        ),
        migrations.AddField(
            model_name='episode',
            name='characters_in_ep',
            field=models.ManyToManyField(to='rick_and_morty.character'),
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date field'),
        ),
        migrations.AddField(
            model_name='episode',
            name='played',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='first_seen_episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rick_and_morty.episode'),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='location',
            field=models.CharField(default='EARTH', max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='status',
            field=models.CharField(choices=[('Dead', 'DEAD'), ('Alive', 'ALIVE')], max_length=20),
        ),
    ]
