# Generated by Django 5.0.7 on 2024-07-17 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rick_and_morty', '0002_remove_character_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='first_seen_episode',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rick_and_morty.episode'),
        ),
    ]
